"""Native popup labels, following the recipe app's interface preference."""
KEYS = ["title", "starting", "unavailable", "retry", "search", "recent", "favorites", "empty", "library", "settings", "import_link", "import", "use_ai", "working", "done", "raw", "failed", "languages", "checking", "unverified", "target", "layout", "online", "offline", "configured", "open_recipe", "refresh"]
LABELS = {
    "en": dict(zip(KEYS, ["Simple Recipes", "Starting recipe service…", "Recipe service unavailable", "Retry", "Search recipes or ingredients…", "Recent recipes", "Favourites", "No matching recipes", "Open recipe library", "AI settings", "Paste a recipe link…", "Import", "Translate with AI", "Importing recipe…", "Recipe imported", "Saved without AI processing", "Import failed. Check the link and try again.", "Check languages", "Checking model languages…", "No verified target languages yet", "Recipe language", "Interface language", "Connected", "Offline", "Configured; connection not checked", "Open recipe", "Refresh"])),
    "de": dict(zip(KEYS, ["Simple Recipes", "Rezeptdienst wird gestartet…", "Rezeptdienst nicht verfügbar", "Erneut versuchen", "Rezepte oder Zutaten suchen…", "Neueste Rezepte", "Favoriten", "Keine passenden Rezepte", "Rezeptsammlung öffnen", "KI-Einstellungen", "Rezeptlink einfügen…", "Importieren", "Mit KI übersetzen", "Rezept wird importiert…", "Rezept importiert", "Ohne KI-Verarbeitung gespeichert", "Import fehlgeschlagen. Link prüfen und erneut versuchen.", "Sprachen prüfen", "Modellsprachen werden geprüft…", "Noch keine geprüften Zielsprachen", "Rezeptsprache", "Oberflächensprache", "Verbunden", "Offline", "Konfiguriert; Verbindung ungeprüft", "Rezept öffnen", "Aktualisieren"])),
    "fr": dict(zip(KEYS, ["Simple Recipes", "Démarrage du service…", "Service de recettes indisponible", "Réessayer", "Rechercher une recette ou un ingrédient…", "Recettes récentes", "Favoris", "Aucune recette correspondante", "Ouvrir la collection", "Paramètres IA", "Coller un lien de recette…", "Importer", "Traduire avec l’IA", "Importation de la recette…", "Recette importée", "Enregistrée sans traitement IA", "Échec de l’importation. Vérifiez le lien et réessayez.", "Vérifier les langues", "Vérification des langues du modèle…", "Aucune langue cible vérifiée", "Langue des recettes", "Langue de l’interface", "Connecté", "Hors ligne", "Configuré ; connexion non vérifiée", "Ouvrir la recette", "Actualiser"])),
    "it": dict(zip(KEYS, ["Simple Recipes", "Avvio del servizio…", "Servizio ricette non disponibile", "Riprova", "Cerca ricette o ingredienti…", "Ricette recenti", "Preferiti", "Nessuna ricetta corrispondente", "Apri la raccolta", "Impostazioni IA", "Incolla un link di ricetta…", "Importa", "Traduci con IA", "Importazione della ricetta…", "Ricetta importata", "Salvata senza elaborazione IA", "Importazione non riuscita. Controlla il link e riprova.", "Verifica le lingue", "Verifica delle lingue del modello…", "Nessuna lingua di destinazione verificata", "Lingua delle ricette", "Lingua dell’interfaccia", "Connesso", "Non in linea", "Configurato; connessione non verificata", "Apri la ricetta", "Aggiorna"])),
    "es": dict(zip(KEYS, ["Simple Recipes", "Iniciando el servicio…", "Servicio de recetas no disponible", "Reintentar", "Buscar recetas o ingredientes…", "Recetas recientes", "Favoritos", "No hay recetas coincidentes", "Abrir la colección", "Ajustes de IA", "Pegar un enlace de receta…", "Importar", "Traducir con IA", "Importando la receta…", "Receta importada", "Guardada sin procesamiento de IA", "Error de importación. Comprueba el enlace e inténtalo de nuevo.", "Comprobar idiomas", "Comprobando los idiomas del modelo…", "Sin idiomas de destino verificados", "Idioma de las recetas", "Idioma de la interfaz", "Conectado", "Sin conexión", "Configurado; conexión sin comprobar", "Abrir receta", "Actualizar"])),
}
